server:
  port: 8001

spring:
  application:
    name: eureka-server-8001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

